### ISSUE TITLE
CORS error when trying to play audio on an imported episode on Publish

### ISSUE THREAD

**Issue by gcampo88** [PRX/play.prx.org#109]
`XMLHttpRequest cannot load https://dovetail-staging.prxu.org/hermoney/34112fe8-6506-4019-ad2f-8643b380ce31/HerMoney-with-Mike-Roizen.mp3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://play-staging.prx.tech' is therefore not allowed access. The response had HTTP status code 404.`

**Comment by kookster** [comment]
This may be a dovetail change to add CORS? @cavis

**Comment by cavis** [comment]
Turns out this is actually a problem with the content-type on the S3 files created by the CMS lambdas.

**Comment by gcampo88** [comment]
closing after https://github.com/PRX/cms-audio-lambda/pull/3 !
