### ISSUE TITLE
Empty placements request (e.g. vanilla) to adzerk returns 400 error

### ISSUE THREAD

**Issue by kookster** [PRX/play.prx.org#111]
When the player makes a POST to `https://engine.adzerk.net/api/v2` with no placements in the request:
```
{"placements":[]}
```
The response from adzerk is a 400 error with the text message:
"Out of 0 placements on the request, none were valid"

This error is not handled, and the player then is unable to playback audio.

@cavis suggests the player should see the empty placement array back from dovetail, and make no request to adzerk

**Comment by cavis** [comment]
[Fixed!](http://play.prx.org/e?uf=http%3A%2F%2Ffeeds.prx.org%2Ftransistor_stem)
