### ISSUE TITLE
mobile safari playlist pull scroll oddness

### ISSUE THREAD

**Issue by kookster** [PRX/play.prx.org#130]
when pulling the list down after it is already at top, pulls the background image down, which rebounds with inertia, but list stays put. same thing happens when you try to drag the player background

**Comment by sandikbarr** [comment]
Is this a duplicate of #129 or something different?

**Comment by pkarman** [comment]
I'm assuming since they were opened on the same day by the same person that they aren't duplicates, but agreed it is hard to tell since #129 has no details.
I'm adding `reviewplx` to both.

**Comment by kookster** [comment]
Looks like my edit on 129 somehow opened 130, closed the dupe #129

**Comment by pkarman** [comment]
@sandikbarr are you able to Estimate this one?

**Comment by sandikbarr** [comment]
@pkarman I can look into it, but not off the top of my head. Haven't worked on the player, but I've worked with it enough to figure it out.

**Comment by sandikbarr** [comment]
@kookster did you see this behavior on someone's playlist in particular? The layout on mobile screen size is not good, but I am not able to recreate this scrolling problem with Mortified at least.
![image](https://user-images.githubusercontent.com/2250413/31102936-00ec8350-a79a-11e7-89f4-0a49ff19413a.png)

**Comment by sandikbarr** [comment]
BTW, this mobile view scrunching is covered in #174 UI collisions. Assigning over to @kookster because I couldn't figure out how to recreate this.

**Comment by kookster** [comment]
seems to be working for me now - I may have been testing when not embedded in a page, perhaps that made a difference
