### ISSUE TITLE
Events logged to GA without show name

### ISSUE THREAD

**Issue by farski** [PRX/play.prx.org#136]
There seems to be a significant number of events getting sent to GA for playback that don't include a `Show Name` metric.

I believe even if there's no explicit `tt` in the query string, it will just pull the show title from the feed. (If there is a `tt` I think it uses that, which may not actually be what we want. Worth discussing.)

**Comment by gcampo88** [comment]
Could that be for when ads are playing? If 1-1 ratio of episode audio to ad audio, percentages could make sense (assuming this is the bit you're looking at?):
![image](https://user-images.githubusercontent.com/16007382/27446037-17929130-574a-11e7-9a59-201be54ba09a.png)

**Comment by farski** [comment]
@gcampo88 I'd have to go back and look more closely, but I thought the title that gets sent with the GA events only gets set once when the player loads. Yours is a good theory, though, so I might be wrong or it might not be behaving that way.

**Comment by gcampo88** [comment]
OK, poked around a bit and I think my theory that it was the ads playing is wrong. My new theory is that when the logger is first created, `ngOnInit()` is called before the feed fetch request has populated the `@Input() title`. So it makes a logger with the `label: undefined`. That logger then gets overwritten in `ngOnChanges()`, but it seems to be hanging around and still sending playback events regardless. 
![image](https://user-images.githubusercontent.com/16007382/27548818-18d0a570-5a68-11e7-843c-3106720bd63e.png)
Just wrapping the first logger creation in an if block solves it. PR coming your way shortly @farski .

**Comment by gcampo88** [comment]
Looks like we can close this @farski ? Not seeing anything with label `(not set)` now

**Comment by farski** [comment]
Hm. I think what we're actually looking at for this one is the `Show Name` custom dimension, and I'm still seeing a decent amount of events getting logged with a blank value for that.

**Comment by gcampo88** [comment]
Not quite sure where to look to find that! Can you send link and/or screenshot?

**Comment by pkarman** [comment]
@farski can this be closed? New issue opened if necessary?

**Comment by farski** [comment]
AFAIK there was still some evidence that this remains an issue.

**Comment by gcampo88** [comment]
@farski can you show a screenshot or link to what you're seeing? I've tried running various Custom Reports to find incidences of `playback` or `waiting` without a Show Name and am not finding them. Have tried setting Show Name as primary dimension, or Episode Title as primary dimension and then adding Show Name as secondary so we might still see events with Ep title but  no Show Name -- still no dice. (E.g.: https://docs.google.com/a/prx.org/spreadsheets/d/1A8LZVTlO_t_xiZQV81B8rYFZq4-vz3GHSSiK46B-rMk/edit?usp=sharing )
