### ISSUE TITLE
Don't over-count podtrac impressions

### ISSUE THREAD

**Issue by gcampo88** [PRX/play.prx.org#155]
- [x] Defer audio requests until playback starts
  - Don't preload mp3 file, which triggers counting in Podtrac
- [x] Display feed itunes-duration as the duration until playback starts
  - Have some default mode where no duration is shown
  - When file loads, then go back to displaying the calculated duration
- [ ] ~~Recognize dovetail urls (probably the regexp in DovetailFetcher) ... and pre-fetch those requests _directly_ from dovetail~~
  - ~~Don't append the `?debug` param, and don't go through podtrac/blubrry/etc~~
  - ~~Use this as the duration (plus the way we pad "num-ads x 10-seconds-each")~~
  - _I've opted to leave this out for now... things work fine just using the itunes duration, which our feeds always set_

**Comment by sandikbarr** [comment]
Is this medium priority? Not sure. @kookster?

**Comment by cavis** [comment]
This will likely require either a new kinesis-logging endpoint within DT itself, or some sort of pixel tracker that can do the same thing.  As we think about a generic pingbacks standard for dovetail, might be a good idea to use that same standard to receive pingbacks within dovetail.

**Comment by cavis** [comment]
Original description:

> For Dovetail audio: the player follows redirects (and hits podtrac-ish counts), but when it gets to DT it hits the "debug" endpoint, which doesn't track impressions or downloads (and shouldn't, since it's also used by backsaw, etc). The player then manually logs impressions to Adzerk as the listener plays the ads - but not to us/ BigQuery.
>
> To be the most accurate, the Player should fire a “Download” to bigquery when you actually press play, and fire impressions to bigquery the same time it logs to adzerk.

**Comment by cavis** [comment]
PRX version fixed!  Forever!
