### ISSUE TITLE
Episode artwork collapses horizontally when title is long 

### ISSUE THREAD

**Issue by gcampo88** [PRX/play.prx.org#158]
Example: 
http://www.storycentral.org/a-filipino-albino-gay-straight-boy-girl-poor-privileged-immigrant-american-life/

Adding some min-width to episode artwork + getting the title text to wrap or ellipsis nicely should do it. We've made a big push on getting shows to use this, and it's now being used in the wild on places like foodandwine.com and lots of show websites, so we should fix this quickly.

**Comment by cavis** [comment]
Confirmed fixes!
