### ISSUE TITLE
Long-term URL

### ISSUE THREAD

**Issue by farski** [PRX/play.prx.org#16]
Presumably we'll be living with the URL for these embeds for a while. Any thoughts on what form they should take, @kookster @cavis ?

**Comment by cavis** [comment]
No strong opinions.  Something short!

What prx domain were you thinking?  I seem to recall some sort of doc outlining which domains are used for what.

**Comment by kookster** [comment]
embed seems like a less than awesome choice, though makes sense as our name for it.

player.prx.org?

different domain entirely?

**Comment by farski** [comment]
The reality of the URLs this thing is going to spit out is that they are going to be hideous. Like hundreds of characters long and completely nonsense to most people. So to that extent I'm not super worried about how user-friendly/marketable they are.

**Comment by farski** [comment]
Not sure about domain. I guess I assumed it would be prx.org, since no other domain we have currently applies.

**Comment by kookster** [comment]
I agree we should use a prx.org url.
I am fine with `player.prx.org` or `play.prx.org` but open to other suggestions.

**Comment by kookster** [comment]
play it is!
