### ISSUE TITLE
Keypress events don't work on player

### ISSUE THREAD

**Issue by gcampo88** [PRX/play.prx.org#166]
The player registers the same keypress listener twice, and some of the actions triggered by keys are toggling. So in some cases, when a key is pressed, the thing in question is toggled and then toggled again immediately. End result is that keypresses don't work. For other actions, the thing is done twice (e.g., seek by -10 sends you back by 20). 

Remove one of the listeners!
https://github.com/PRX/play.prx.org/blob/8283ee47212c719415ca02bd901940ddd7acb92f/src/app/shared/player/player.component.html

**Comment by cavis** [comment]
Deployed to PRX version!
