### ISSUE TITLE
UI collisions

### ISSUE THREAD

**Issue by farski** [PRX/play.prx.org#174]
When the player gets crunched horizontally the logo is overlapping other UI elements

![screen shot 2017-11-02 at 9 12 46 am](https://user-images.githubusercontent.com/3483/32327767-14ffce2a-bfae-11e7-9b10-2dd4e7fca059.png)

And if it gets even narrower buttons start to fall off the edge

![screen shot 2017-11-02 at 9 14 47 am](https://user-images.githubusercontent.com/3483/32327836-4ad727f0-bfae-11e7-8768-fbfeeb0ddb28.png)

**Comment by kookster** [comment]
the designs kyle is working on will impact the logo and those buttons; we should take this up when those changes get made

**Comment by gcampo88** [comment]
This is out in the while on a few RT producer sites and looks pretty icky -- would be good to fix soon. Bumping priority + putting in Zadie for now.
