### ISSUE TITLE
Deployment steps?

### ISSUE THREAD

**Issue by smilingpeanut** [PRX/play.prx.org#185]
If I wanted to deploy this in production, what would be the steps necessary to do so?

**Comment by kookster** [comment]
Lots of ways you could do so - 

At PRX we build it as a docker image and then deploy to AWS ECS, where the container runs `/bin/application serve` to serve it up.

I think RadioPublic builds the js and deploys the static files (to s3?) with cloudfront, but I'm not positive that's their setup now.

**Comment by kookster** [comment]
You may also want to consider using the player as hosted by RadioPublic as they have gotten their domain/version of the player whitelisted on places like Medium and wordpress.com, but happy to have more folks deploy and use this project!

**Comment by smilingpeanut** [comment]
Thanks for the reply! We're wanting to deploy a separate instance because we're launching a podcast network and we'd like to use a branded player.

I'm a PHP developer, so this Node stuff is a little new for me. :)
