### ISSUE TITLE
For playlist, play in `serial` or `episodic` order

### ISSUE THREAD

**Issue by kookster** [PRX/play.prx.org#187]
via Jonathan Messinger from Gen-Z:

> Hi!
> 
> We're using the PRX playlists (made using https://play.prx.org/) on our new site, Best Robot Ever (http://bestrobotever.com) . And while I realize we're probably unique in this respect, I was wondering > if there's a way to have the playlist start at episode 1 and progress, rather than the most recent episode? For our serialized shows, I think this makes the most sense for our audience.
> 
> Totally understand if this isn't a capability right now, but figured I'd ask. Thanks!

Steps:

- [x] Look for feeds with a serial `<itunes:type>` in the FeedAdapter.
- [x] If set, order the episodes by oldest-episode-first (whether in single-episode or playlist mode)
- [x] Add a query parameter to the player for "season number".  If set, also filter the FeedAdapter episodes to only be that season (`<itunes:season>`).

**Comment by farski** [comment]
I heard from someone else today who was looking for this

**Comment by cavis** [comment]
Yet another support request has come up for this.  Upping the priority!
