### ISSUE TITLE
Playlist player

### ISSUE THREAD

**Issue by kookster** [PRX/play.prx.org#20]
Have a player able to play multiple audio files / podcast episodes.

Start with an RSS Feed to create the playlist player.

Player could be generic as to playlist src, and builder could provide the list via reading rss and passing playlist data on to player.

Future versions could also support selecting specific episodes only, perhaps across feeds?

**Comment by gcampo88** [comment]
here's design -- first round, no need for the "Why you should listen" section. 
![image](https://cloud.githubusercontent.com/assets/16007382/25748641/c225cee2-3179-11e7-9521-ac07a6129212.png)

**Comment by cavis** [comment]
Deployed!
