### ISSUE TITLE
Refactored app template review

### ISSUE THREAD

**Issue by farski** [PRX/play.prx.org#239]
See PRX/internal#696. Provide the results for this app in this issue.

**Comment by cavis** [comment]
- [ ] CPU and memory for all task definitions
- [ ] Desired count for all ECS services
- [ ] Correct listener rules and priorities
- [ ] All tags
- [ ] Stack description
- [ ] Log group retention
- [ ] Alarms (missing alarms, unnecessary alarms, incorrectly configured alarms, etc)
- [ ] Alarm names and descriptions
- [ ] Look for anything that look problematic for multi-region (e.g., hard-coded regions, etc)
- [ ] Environment variables moved from secrets to the template
- [ ] Target group health checks and deregistration values
- [ ] Missing resource/components (compare to old template)
- [ ] TODOs and tktk
