### ISSUE TITLE
Skip +30

### ISSUE THREAD

**Issue by kookster** [PRX/play.prx.org#34]
Skip buttons are useful, but space is always a concern.

We agreed a skip back 10 secs button makes sense to start, as the most likely to be used for the "I missed that" scenario with spoken word podcasts.

Also have to consider that a skip ahead button may encourage skipping ads.
We don't want to prevent that at this point, but we also don't have to make it as easy as possible.

**Comment by kookster** [comment]
new player design includes a skip 30 forward, and makes some of the control buttons responsive (they only show when the player is wide enough for all controls).

Based on that, we should add a skip 30 fwd, and see how that goes

**Comment by kookster** [comment]
I think we did this right @gcampo88? close if you did pls

**Comment by gcampo88** [comment]
Yup! Closing.
