### ISSUE TITLE
Download audio

### ISSUE THREAD

**Issue by kookster** [PRX/play.prx.org#42]
How/should we provide a means to download the audio file.

I am not a huge fan of this:
- not useful on mobile
- on desktop, if you want it offline -> subscribe

**Comment by farski** [comment]
I can't think of any reasons why we'd support this, and many reasons not to.

**Comment by kookster** [comment]
for a desktop player, this is useful, and now included in the designs as a possible button that can be configured

**Comment by gcampo88** [comment]
Done as of #163!
