### ISSUE TITLE
Use explicit mode rather than strictly size/scale to determine layout

### ISSUE THREAD

**Issue by kookster** [PRX/play.prx.org#51]
Update the player's responsive media rules to instead use an explicit indication of horizontal vs. vertical layout.

Player is currently responsive, and changes to a different 'vertical' layout when the height is past a certain point. The new design includes a larger text component at the bottom of the player controls which would lead to a size that would 'trip' this different layout, but should not.

**Comment by gcampo88** [comment]
I think this is done, unless I'm reading this wrong. The embeddable player iframe that can be built through play.prx.org or through publish.prx.org has explicit size settings (all have the same height, and the user can set width as fixed or expanding to size of window); sans iframe, the player itself remains responsive. OK to close @kookster or have I misunderstood the ticket?

**Comment by kookster** [comment]
This was back when the player supported a square mode, and it was desirable to change between them automatically. We killed the square, so this is n/a, closing.
