### ISSUE TITLE
Rethink buttons for player

### ISSUE THREAD

**Issue by gcampo88** [PRX/play.prx.org#68]
- [ ] button that looks like download is actually a link to subscribe
- [ ] button that looks like upload is actually a link to share an embeddable iframe

One idea: to have a palette of buttons available to user as user is building / customizing player:
- Could have booleans (show or don't) for: volume control (currently not in player), playback speed (capability is there but button currently is not). 
- For subscribe + share buttons, could have more customization options: which image do you want for the button, what link should be used (potentially could vary based on client)
- logo: perhaps we should build in an empty/transparent logo that user can replace with their own image

**Comment by gcampo88** [comment]
Status update as of 11/14: consensus with @kookster is that it's best to hold off on doing anything on this front until after we do some user testing with RT producers later this week and see what they want from these buttons. So putting this on back burner for now!

**Comment by kookster** [comment]
More votes from user testing for changing these:
"I think of the down button as a download button, not subscribe."
"And I think of the other as an upload, doesn't look like share - should have a sideways swoosh."

**Comment by kookster** [comment]
Consult with @farski and see if we can figure out better icons for both

**Comment by farski** [comment]
Share I think we can work out pretty easily, but subscribe is going to be a hard icon to find without context, I think. Even TY has to use a button with the word _Subscribe_ in it.

**Comment by gcampo88** [comment]
agreed. Well, the "share" one is definitely the one we've gotten the most feedback about, so swapping that one out is a great start. and for subscribe: @kookster wanted to avoid the RSS symbol... maybe something like an envelope? what do you think?

**Comment by farski** [comment]
If I see an envelope I expect to send an email, which seems like a sharing function.

**Comment by gcampo88** [comment]
Yeah, that makes sense. Hmm. any other ideas? 
Also, oops, I misspoke before -- the "subscribe" is indeed the one we get the most feedback about (it's the one that looks like a download button now)

**Comment by gcampo88** [comment]
Just perused a whole bunch. I agree that a closed envelope looks like sending/ receiving an email-- but maybe an open envelope with something being deposited in it, like this?:
<img width="274" alt="screen shot 2017-01-26 at 3 15 29 pm" src="https://cloud.githubusercontent.com/assets/16007382/22348611/618e127a-e3da-11e6-9354-d1b22906cbe3.png">

**Comment by gcampo88** [comment]
@farski sounds like we're going to go with a plus sign icon for now, and see what feedback we get on it! Do you have a library of svg icons you pull from? Or, if you've been making the svgs we use ourselves and are self-taught, do you have any learn-to-make-an-svg resources you'd recommend?

**Comment by farski** [comment]
@gcampo88 Sometimes I will find icons online, but I don't have a go-to resource, and it's rare that a found icon will match the ones we got from Rodrigo close enough, so I often end up making them. I usually just use [Affinity Designer](https://affinity.serif.com/en-us/designer/) which has a pretty good SVG export.

**Comment by gcampo88** [comment]
thank you for the info! Hmm -- no free options you'd recommend?

**Comment by farski** [comment]
I don't have any free recommendations, but that doesn't mean they're not out there

**Comment by gcampo88** [comment]
okay, took a shot at it! #101
