### ISSUE TITLE
Scrubber bar design difficult to understand

### ISSUE THREAD

**Issue by kookster** [PRX/play.prx.org#76]
unclear where the "thumb" is, and where in the file the user is scrubbing to, also pretty thin making it difficult to actually click on and do the scrubbing.

consider making it wider on hover, or making the active area for scrubbing larger, even if the bar itself remains thin, or some other idea not listed here.

**Comment by kookster** [comment]
I believe this is being address by an on hover enlargement, yes @gcampo88 ?

**Comment by gcampo88** [comment]
@kookster I made the scrubber bigger and fixed the location of the :hover line (used to be slightly off from where cursor was) -- should I add hover enlargement as well?
