### ISSUE TITLE
podcast feed should be remembered

### ISSUE THREAD

**Issue by chrisrhoden** [PRX/play.prx.org#9]

**Comment by kookster** [comment]
was this for the builder or player? Is this for the player to remember the podcast this episode audio came from?

**Comment by chrisrhoden** [comment]
this was for the builder - something you said about being able to avoid pasting in an RSS feed every time you come to the builder page

**Comment by kookster** [comment]
ah, yes, I sorta remember that - I think I was trying to figure out a way a
producer of a show wouldn't have to keep entering their rss feed url every
time they want to build a player for that feed, ok, thanks for the reminder!

**Comment by kookster** [comment]
You can pass in the rss feed url in the url request, good enough to bookmark
