### ISSUE TITLE
Change PRX logo to a b&w or "watermark" version

### ISSUE THREAD

**Issue by kookster** [PRX/play.prx.org#90]
it's distracting with the orange and blue, I think this would work better looking like a watermark, like embossed b&w image with transparency

**Comment by gcampo88** [comment]
Altered the colors in the existing .svg file-- thoughts? 

<img width="691" alt="screen shot 2017-01-17 at 1 14 03 pm" src="https://cloud.githubusercontent.com/assets/16007382/22033544/e5a5231c-dcb6-11e6-9715-c87f53af0e8a.png">
<img width="1213" alt="screen shot 2017-01-17 at 1 14 12 pm" src="https://cloud.githubusercontent.com/assets/16007382/22033543/e5a4f3ba-dcb6-11e6-97a0-b3e093e2faf0.png">

**Comment by cavis** [comment]
done!
